baseURL = 'https://x666ep.github.io/staff-core-architectural-analysis'
canonifyURLs = true
languageCode = 'ru-ru'
title = 'Staff Core APIq'

theme = "reveal-hugo"

codeFences = true

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


[params.reveal_hugo]
custom_theme = "stylesheets/custom_white.css"
slide_number = true
